[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = true
fs_permissions = [{ access = "read-write", path = "./script/" }]

# EIP-7702 specific settings
evm_version = "cancun" # Latest EVM version for cutting-edge features

# Testing configuration
gas_reports = ["*"]
gas_limit = 30_000_000


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
